files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        de-DE: de
        es-ES: es
        fr-FR: fr
        it-IT: it
        sr-CS: sr
