name: Bump version

on:
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        description: "Tags version as a beta for testing"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bumpver
        run: pip install bumpver
      - name: Configure git user
        run: |
          git config user.email "github-actions"
          git config user.name "github-actions@github.com"
      - name: Update version
        if: github.ref == 'refs/heads/main'
        run: |
          if ${{ github.event.inputs.prerelease }}
            make pre-release
          else
            make release
          fi
