name: Bump version

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bumpver
        run: pip install bumpver
      - name: Update version
        if: github.ref == 'refs/heads/main'
        run: make release
