name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.185.0
      - name: Setup Fastlane
        run: bundle install
      - name: Run tests
        run: make test
